# Breaking changes in 2.0 update:
# - tiers are stored under the "tiers" folder
# - the "commands" section for rewards has been replaced with "actions" and accepts ActionUtil strings

gui:
  title: "&6Daily Rewards &2[Tier %tier%]"
  cooldown: "&cYou can't claim this reward for %time%"

messages:
  no_console: "&cYou must be a player to use this command"
  claimed_reward: "&aYou claimed reward %reward%"
  cannot_claim: "&cYou cannot claim this reward"

claims:
  # Cooldown in seconds before a player can claim another reward
  # Default: 1 day
  cooldown: 86400
  # The time after which a player's streak will reset if they do not claim a reward
  # Default: 2 days
  max: 172800