rewards:
  tiers:
    1:
      0:
        material: DIRT
        data: 0
        lore:
        - "&6Example &2lore"
        name: "&eDirt Reward"
        commands:
        - "give %player% dirt 1"
      1:
        material: COAL_BLOCK
        data: 0
        lore:
        - "&6Example &2lore"
        name: "&eCoal Reward"
        commands:
        - "give %player% coal 1"
      2:
        material: IRON_BLOCK
        data: 0
        lore:
        - "&6Example &2lore"
        name: "&eIron Reward"
        commands:
        - "give %player% iron_ingot 1"
      3:
        material: GOLD_BLOCK
        data: 0
        lore:
        - "&6Example &2lore"
        name: "&eGold Reward"
        commands:
        - "give %player% gold_ingot 1"
      4:
        material: LAPIS_BLOCK
        data: 0
        lore:
        - "&6Example &2lore"
        name: "&eLapis Reward"
        commands:
        - "give %player% diamond 1"
      5:
        material: DIAMOND_BLOCK
        data: 0
        lore:
        - "&6Example &2lore"
        name: "&bDiamond Reward"
        commands:
        - "give %player% diamond 1"
      6:
        material: EMERALD_BLOCK
        data: 0
        lore:
        - "&6Example &2lore"
        name: "&aEmerald Reward"
        commands:
        - "give %player% emerald 1"
    2:
      0:
        material: GRASS
        data: 0
        lore:
        - "&aGrass Reward"
        name: "Tier 2 Reward"
        commands:
        - "give %player% dirt 1"
      1:
        material: GRASS
        data: 0
        lore:
        - "&aGrass Reward"
        name: "Tier 2 Reward"
        commands:
        - "give %player% dirt 1"
      2:
        material: GRASS
        data: 0
        lore:
        - "&aGrass Reward"
        name: "Tier 2 Reward"
        commands:
        - "give %player% dirt 1"
      3:
        material: GRASS
        data: 0
        lore:
        - "&aGrass Reward"
        name: "Tier 2 Reward"
        commands:
        - "give %player% dirt 1"
      4:
        material: GRASS
        data: 0
        lore:
        - "&aGrass Reward"
        name: "Tier 2 Reward"
        commands:
        - "give %player% dirt 1"
      5:
        material: GRASS
        data: 0
        lore:
        - "&aGrass Reward"
        name: "Tier 2 Reward"
        commands:
        - "give %player% dirt 1"
      6:
        material: GRASS
        data: 0
        lore:
        - "&aGrass Reward"
        name: "Tier 2 Reward"
        commands:
        - "give %player% dirt 1"

gui:
  title: "&6Daily Rewards &2[Tier %tier%]"
  cooldown: "&cYou can't claim this reward for %time%"

messages:
  no_console: "&cYou must be a player to use this command"
  claimed_reward: "&aYou claimed reward %reward%"
  cannot_claim: "&cYou cannot claim this reward"

claims:
  # Cooldown in seconds before a player can claim another reward
  # Default: 1 day
  cooldown: 86400
  # The time after which a player's streak will reset if they do not claim a reward
  # Default: 2 days
  max: 172800