name: DailyRewards
author: Mas281
version: ${project.version}

depend: [ActionUtil]
main: me.itsmas.dailyrewards.DailyRewards
api-version: 1.14

commands:
  rewards:
    aliases: [dailyreward, dailyrewards, dr]